import './index.pug'
import './scss/style.scss'
import './img/clock.png'
// import './ts/startWith'
// import './ts/endWith'
// import './ts/lab-startwith'
// import './ts/combineLatest'
// import './ts/combineLatest-2'
// import './ts/forkJoin' 
// import './ts/forkJoin-2' 
import './ts/forkJoin-3' 