import './index.pug'
import './scss/style.scss'
import './img/clock.png'
// import './ts/fetch'
// import './ts/ajaxRxjs'
// import './ts/getJSON'
// import './ts/apiGithub'
// import './ts/mergeMap'
// import './ts/switchMap-2'
// import './ts/switchMap-3'
// import './ts/mergeMapvsSwitchMap'
// import './ts/contactMap'
// import './ts/exhaustMap'

// Ejercicios repaso