import './index.pug'
import './scss/style.scss'
import './img/clock.png'
// import './ts/01-capitalizar'
// import './ts/02-reduce'
// import './ts/03--randoms'
// import './ts/04-cuenta-regresiva'
// import './ts/05-combinar'
import './ts/06-luke-skywalker'