import './index.pug'
import './scss/style.scss'
import './img/clock.png'
import './ts/clock'
// import './ts/status-bar'
// import './ts/reduce'
// import './ts/scan'
// import './ts/scanRedux'
// import './ts/subject-example'